apiVersion: v1
kind: Service
metadata:  
  name: my-nodeport-service
spec:
  hostNetwork: true
  selector:    
    app: quizapp
  type: NodePort
  ports:  
  - name: http
    port: 8000
    targetPort: 3000
    nodePort: 30036
    protocol: TCP