apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: quizapp
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 3000
  type: LoadBalancer
